// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoEncontros.Infraestrutura.Dados;

#nullable disable

namespace ProjetoEncontros.Infraestrutura.Dados.Migracoes
{
    [DbContext(typeof(ContextoDeBanco))]
    [Migration("20260728132614_PreferenciasDoAniversario")]
    partial class PreferenciasDoAniversario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoEncontros.Dominio.Arquivos.ArquivoArmazenado", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset?>("AtivadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ativado_em");

                    b.Property<string>("ChaveDoObjeto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("chave_do_objeto");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("ETag")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("etag");

                    b.Property<DateTimeOffset?>("ExcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("excluido_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("Finalidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("finalidade");

                    b.Property<Guid?>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoRecurso")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_recurso");

                    b.Property<Guid>("IdentificadorDoUsuarioResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_responsavel");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<long?>("TamanhoConfirmadoEmBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_confirmado_em_bytes");

                    b.Property<long>("TamanhoReservadoEmBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_reservado_em_bytes");

                    b.Property<int>("TentativasDeExclusao")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_de_exclusao");

                    b.Property<string>("TipoDeConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_de_conteudo");

                    b.Property<string>("UltimoErroDeExclusao")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ultimo_erro_de_exclusao");

                    b.HasKey("Identificador");

                    b.HasIndex("ChaveDoObjeto")
                        .IsUnique();

                    b.HasIndex("IdentificadorDoEncontro");

                    b.HasIndex("IdentificadorDoRecurso");

                    b.HasIndex("IdentificadorDoUsuarioResponsavel");

                    b.HasIndex("Situacao", "ExpiraEm");

                    b.ToTable("arquivos_armazenados", null, t =>
                        {
                            t.HasCheckConstraint("ck_arquivos_armazenados_confirmacao_por_situacao", "(situacao IN ('Ativo', 'ExclusaoPendente', 'Excluido') AND tamanho_confirmado_em_bytes IS NOT NULL) OR (situacao IN ('Reservado', 'Expirado', 'Cancelado') AND tamanho_confirmado_em_bytes IS NULL)");

                            t.HasCheckConstraint("ck_arquivos_armazenados_encontro", "(finalidade = 'FotoDePerfil' AND identificador_do_encontro IS NULL) OR (finalidade IN ('ImagemDeCapaDoEncontro', 'MidiaDeMemoria') AND identificador_do_encontro IS NOT NULL)");

                            t.HasCheckConstraint("ck_arquivos_armazenados_exclusao", "(situacao = 'Excluido' AND excluido_em IS NOT NULL) OR (situacao <> 'Excluido' AND excluido_em IS NULL)");

                            t.HasCheckConstraint("ck_arquivos_armazenados_expiracao", "expira_em > criado_em");

                            t.HasCheckConstraint("ck_arquivos_armazenados_finalidade", "finalidade IN ('FotoDePerfil', 'ImagemDeCapaDoEncontro', 'MidiaDeMemoria')");

                            t.HasCheckConstraint("ck_arquivos_armazenados_situacao", "situacao IN ('Reservado', 'Ativo', 'ExclusaoPendente', 'Excluido', 'Expirado', 'Cancelado')");

                            t.HasCheckConstraint("ck_arquivos_armazenados_tamanho_confirmado", "tamanho_confirmado_em_bytes IS NULL OR tamanho_confirmado_em_bytes > 0");

                            t.HasCheckConstraint("ck_arquivos_armazenados_tamanho_confirmado_na_reserva", "tamanho_confirmado_em_bytes IS NULL OR tamanho_confirmado_em_bytes <= tamanho_reservado_em_bytes");

                            t.HasCheckConstraint("ck_arquivos_armazenados_tamanho_reservado", "tamanho_reservado_em_bytes > 0");

                            t.HasCheckConstraint("ck_arquivos_armazenados_tentativas", "tentativas_de_exclusao >= 0");
                        });
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Arquivos.CotaDeArmazenamento", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<bool>("AlertaDeCemPorCentoEmitido")
                        .HasColumnType("boolean")
                        .HasColumnName("alerta_de_cem_por_cento_emitido");

                    b.Property<bool>("AlertaDeOitentaPorCentoEmitido")
                        .HasColumnType("boolean")
                        .HasColumnName("alerta_de_oitenta_por_cento_emitido");

                    b.Property<bool>("AvisoDeSetentaPorCentoEmitido")
                        .HasColumnType("boolean")
                        .HasColumnName("aviso_de_setenta_por_cento_emitido");

                    b.Property<long>("BytesAtivos")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_ativos");

                    b.Property<long>("BytesReservados")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_reservados");

                    b.Property<long>("LimiteEmBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("limite_em_bytes");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel");

                    b.HasKey("Identificador");

                    b.ToTable("cotas_de_armazenamento", null, t =>
                        {
                            t.HasCheckConstraint("ck_cotas_bytes_ativos", "bytes_ativos >= 0");

                            t.HasCheckConstraint("ck_cotas_bytes_reservados", "bytes_reservados >= 0");

                            t.HasCheckConstraint("ck_cotas_identificador_padrao", "identificador = 'ef873d3a-0fd7-4b91-845b-c8d181be42da'::uuid");

                            t.HasCheckConstraint("ck_cotas_limite_padrao", "limite_em_bytes = 8589934592");

                            t.HasCheckConstraint("ck_cotas_limite_positivo", "limite_em_bytes > 0");

                            t.HasCheckConstraint("ck_cotas_nivel", "nivel IN ('Normal', 'Aviso', 'Critico', 'Esgotado')");

                            t.HasCheckConstraint("ck_cotas_total", "bytes_ativos <= limite_em_bytes - bytes_reservados");
                        });

                    b.HasData(
                        new
                        {
                            Identificador = new Guid("ef873d3a-0fd7-4b91-845b-c8d181be42da"),
                            AlertaDeCemPorCentoEmitido = false,
                            AlertaDeOitentaPorCentoEmitido = false,
                            AvisoDeSetentaPorCentoEmitido = false,
                            BytesAtivos = 0L,
                            BytesReservados = 0L,
                            LimiteEmBytes = 8589934592L,
                            Nivel = "Normal"
                        });
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Autenticacao.TokenDeAtualizacao", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("HashDoToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_do_token");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.HasKey("Identificador");

                    b.HasIndex("HashDoToken")
                        .IsUnique();

                    b.HasIndex("IdentificadorDoUsuario");

                    b.ToTable("tokens_de_atualizacao", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ConviteDoEncontroPorLink", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("HashDoToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash_do_token")
                        .IsFixedLength();

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuarioQueCriou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_criou");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.HasKey("Identificador");

                    b.HasIndex("HashDoToken")
                        .IsUnique();

                    b.HasIndex("IdentificadorDoEncontro")
                        .IsUnique()
                        .HasFilter("revogado_em IS NULL");

                    b.HasIndex("IdentificadorDoUsuarioQueCriou");

                    b.ToTable("convites_do_encontro_por_link", null, t =>
                        {
                            t.HasCheckConstraint("ck_convites_encontro_link_expiracao", "expira_em > criado_em");

                            t.HasCheckConstraint("ck_convites_encontro_link_revogacao", "revogado_em IS NULL OR revogado_em >= criado_em");
                        });
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.Encontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuarioQueCriou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_criou");

                    b.Property<DateTimeOffset>("InicioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<string>("Tipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlDaImagemDeCapa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_da_imagem_de_capa");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioQueCriou");

                    b.HasIndex("IdentificadorDoGrupo", "Situacao", "InicioEm");

                    b.ToTable("encontros", null, t =>
                        {
                            t.HasCheckConstraint("ck_encontros_coordenadas_completas", "(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)");

                            t.HasCheckConstraint("ck_encontros_coordenadas_exigem_local", "latitude IS NULL OR (local IS NOT NULL AND btrim(local) <> '')");

                            t.HasCheckConstraint("ck_encontros_faixa_da_latitude", "latitude IS NULL OR (latitude >= -90 AND latitude <= 90)");

                            t.HasCheckConstraint("ck_encontros_faixa_da_longitude", "longitude IS NULL OR (longitude >= -180 AND longitude <= 180)");
                        });
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ItemDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuarioQueCriou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_criou");

                    b.Property<Guid?>("IdentificadorDoUsuarioResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_responsavel");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioQueCriou");

                    b.HasIndex("IdentificadorDoUsuarioResponsavel");

                    b.HasIndex("IdentificadorDoEncontro", "Situacao", "CriadoEm");

                    b.ToTable("itens_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MemoriaDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuarioQuePublicou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_publicou");

                    b.Property<string>("Legenda")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("legenda");

                    b.Property<DateTimeOffset?>("RemovidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removida_em");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioQuePublicou");

                    b.HasIndex("IdentificadorDoEncontro", "CriadoEm");

                    b.ToTable("memorias_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MidiaDaMemoria", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDaMemoria")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_da_memoria");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original");

                    b.Property<long>("TamanhoEmBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_em_bytes");

                    b.Property<string>("TipoDeConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_de_conteudo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDaMemoria");

                    b.ToTable("midias_da_memoria", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ParticipanteDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("ConvidadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("convidado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<DateTimeOffset?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondido_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<DateTimeOffset>("VisualizadoAteEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visualizado_ate_em");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoEncontro", "IdentificadorDoUsuario")
                        .IsUnique();

                    b.HasIndex("IdentificadorDoEncontro", "Situacao");

                    b.HasIndex("IdentificadorDoUsuario", "Situacao");

                    b.ToTable("participantes_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PresencaNoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoMembroDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_membro_do_grupo");

                    b.Property<DateTimeOffset>("RespondidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondido_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoMembroDoGrupo");

                    b.HasIndex("IdentificadorDoEncontro", "IdentificadorDoMembroDoGrupo")
                        .IsUnique();

                    b.ToTable("presencas_no_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PublicacaoDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("EhAtualizacaoDoSistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("eh_atualizacao_do_sistema");

                    b.Property<Guid?>("IdentificadorDaPublicacaoRespondida")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_da_publicacao_respondida");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuarioAutor")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_autor");

                    b.Property<string>("NomeOriginalDaMidia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original_da_midia");

                    b.Property<DateTimeOffset>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.Property<DateTimeOffset?>("RemovidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removida_em");

                    b.Property<long?>("TamanhoDaMidiaEmBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_da_midia_em_bytes");

                    b.Property<string>("Texto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("texto");

                    b.Property<string>("TipoDeConteudoDaMidia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_de_conteudo_da_midia");

                    b.Property<string>("UrlDaMidia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_da_midia");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDaPublicacaoRespondida");

                    b.HasIndex("IdentificadorDoUsuarioAutor");

                    b.HasIndex("IdentificadorDoEncontro", "PublicadoEm");

                    b.HasIndex("IdentificadorDoEncontro", "UrlDaMidia");

                    b.ToTable("publicacoes_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.ConviteDoGrupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset?>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EmailConvidado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_convidado");

                    b.Property<DateTimeOffset?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuarioQueConvidou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_convidou");

                    b.Property<DateTimeOffset?>("RecusadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recusado_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("EmailConvidado");

                    b.HasIndex("IdentificadorDoUsuarioQueConvidou");

                    b.HasIndex("IdentificadorDoGrupo", "EmailConvidado", "Situacao");

                    b.ToTable("convites_do_grupo", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("IdentificadorDoUsuarioDono")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_dono");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioDono");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("EntrouEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrou_em");

                    b.Property<Guid>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<DateTimeOffset?>("RemovidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removido_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuario");

                    b.HasIndex("IdentificadorDoGrupo", "IdentificadorDoUsuario")
                        .IsUnique();

                    b.ToTable("membros_do_grupo", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Notificacoes.NotificacaoDoUsuario", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<string>("ChaveDeIdempotencia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_de_idempotencia");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<Guid?>("IdentificadorDoConvite")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_convite");

                    b.Property<Guid?>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid?>("IdentificadorDoItem")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_item");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<DateTimeOffset?>("LidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lida_em");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("mensagem");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("tipo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titulo");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoEncontro");

                    b.HasIndex("IdentificadorDoItem");

                    b.HasIndex("IdentificadorDoUsuario");

                    b.HasIndex("IdentificadorDoUsuario", "ChaveDeIdempotencia")
                        .IsUnique()
                        .HasFilter("chave_de_idempotencia IS NOT NULL");

                    b.HasIndex("IdentificadorDoUsuario", "CriadoEm");

                    b.HasIndex("IdentificadorDoUsuario", "Situacao");

                    b.ToTable("notificacoes_do_usuario", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Notificacoes.PreferenciaDeNotificacaoDoUsuario", b =>
                {
                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<DateTimeOffset>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizada_em");

                    b.Property<bool>("LembretesDeEncontroAtivos")
                        .HasColumnType("boolean")
                        .HasColumnName("lembretes_de_encontro_ativos");

                    b.Property<bool>("NotificacoesDeAlteracaoAtivas")
                        .HasColumnType("boolean")
                        .HasColumnName("notificacoes_de_alteracao_ativas");

                    b.Property<bool>("NotificacoesDeCombinadosAtivas")
                        .HasColumnType("boolean")
                        .HasColumnName("notificacoes_de_combinados_ativas");

                    b.Property<bool>("NotificacoesDeConviteAtivas")
                        .HasColumnType("boolean")
                        .HasColumnName("notificacoes_de_convite_ativas");

                    b.HasKey("IdentificadorDoUsuario");

                    b.ToTable("preferencias_de_notificacao_do_usuario", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<string>("UrlDaFotoDePerfil")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_da_foto_de_perfil");

                    b.HasKey("Identificador");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Autenticacao.TokenDeAtualizacao", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ConviteDoEncontroPorLink", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueCriou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.Encontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueCriou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ProjetoEncontros.Dominio.Encontros.LocalizacaoDoEncontro", "Localizacao", b1 =>
                        {
                            b1.Property<Guid>("EncontroIdentificador")
                                .HasColumnType("uuid");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("local");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");

                            b1.HasKey("EncontroIdentificador");

                            b1.ToTable("encontros");

                            b1.WithOwner()
                                .HasForeignKey("EncontroIdentificador");
                        });

                    b.OwnsOne("ProjetoEncontros.Dominio.Encontros.PreferenciasDoAniversario", "PreferenciasDoAniversario", b1 =>
                        {
                            b1.Property<Guid>("EncontroIdentificador")
                                .HasColumnType("uuid");

                            b1.Property<string>("CoisasQueGostariaDeGanhar")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("coisas_que_gostaria_de_ganhar");

                            b1.Property<string>("NumeroDoCalcado")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("numero_do_calcado");

                            b1.Property<string>("SugestoesDePresente")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("sugestoes_de_presente");

                            b1.Property<string>("TamanhoDaCalca")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("tamanho_da_calca");

                            b1.Property<string>("TamanhoDaCamiseta")
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("tamanho_da_camiseta");

                            b1.HasKey("EncontroIdentificador");

                            b1.ToTable("encontros");

                            b1.WithOwner()
                                .HasForeignKey("EncontroIdentificador");
                        });

                    b.Navigation("Localizacao");

                    b.Navigation("PreferenciasDoAniversario");
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ItemDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueCriou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioResponsavel")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MemoriaDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQuePublicou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MidiaDaMemoria", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.MemoriaDoEncontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDaMemoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ParticipanteDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PresencaNoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoMembroDoGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PublicacaoDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.PublicacaoDoEncontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDaPublicacaoRespondida")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.ConviteDoGrupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany("Convites")
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueConvidou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioDono")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany("Membros")
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Notificacoes.NotificacaoDoUsuario", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoEncontros.Dominio.Encontros.ItemDoEncontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoItem")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Notificacoes.PreferenciaDeNotificacaoDoUsuario", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.Navigation("Convites");

                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
