// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoEncontros.Infraestrutura.Dados;

#nullable disable

namespace ProjetoEncontros.Infraestrutura.Dados.Migracoes
{
    [DbContext(typeof(ContextoDeBanco))]
    [Migration("20260713111736_V031MidiasNoFeedDoEncontro")]
    partial class V031MidiasNoFeedDoEncontro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoEncontros.Dominio.Autenticacao.TokenDeAtualizacao", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("HashDoToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_do_token");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.HasKey("Identificador");

                    b.HasIndex("HashDoToken")
                        .IsUnique();

                    b.HasIndex("IdentificadorDoUsuario");

                    b.ToTable("tokens_de_atualizacao", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.Encontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<Guid?>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuarioQueCriou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_criou");

                    b.Property<DateTimeOffset>("InicioEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio_em");

                    b.Property<string>("Local")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("local");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("titulo");

                    b.Property<string>("UrlDaImagemDeCapa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_da_imagem_de_capa");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioQueCriou");

                    b.HasIndex("IdentificadorDoGrupo", "Situacao", "InicioEm");

                    b.ToTable("encontros", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ItemDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuarioQueCriou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_criou");

                    b.Property<Guid?>("IdentificadorDoUsuarioResponsavel")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_responsavel");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioQueCriou");

                    b.HasIndex("IdentificadorDoUsuarioResponsavel");

                    b.HasIndex("IdentificadorDoEncontro", "Situacao", "CriadoEm");

                    b.ToTable("itens_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MemoriaDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuarioQuePublicou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_publicou");

                    b.Property<string>("Legenda")
                        .HasMaxLength(280)
                        .HasColumnType("character varying(280)")
                        .HasColumnName("legenda");

                    b.Property<DateTimeOffset?>("RemovidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removida_em");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioQuePublicou");

                    b.HasIndex("IdentificadorDoEncontro", "CriadoEm");

                    b.ToTable("memorias_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MidiaDaMemoria", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDaMemoria")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_da_memoria");

                    b.Property<string>("NomeOriginal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original");

                    b.Property<long>("TamanhoEmBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_em_bytes");

                    b.Property<string>("TipoDeConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_de_conteudo");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDaMemoria");

                    b.ToTable("midias_da_memoria", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ParticipanteDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("ConvidadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("convidado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<DateTimeOffset?>("RespondidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondido_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoEncontro", "IdentificadorDoUsuario")
                        .IsUnique();

                    b.HasIndex("IdentificadorDoEncontro", "Situacao");

                    b.HasIndex("IdentificadorDoUsuario", "Situacao");

                    b.ToTable("participantes_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PresencaNoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoMembroDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_membro_do_grupo");

                    b.Property<DateTimeOffset>("RespondidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("respondido_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoMembroDoGrupo");

                    b.HasIndex("IdentificadorDoEncontro", "IdentificadorDoMembroDoGrupo")
                        .IsUnique();

                    b.ToTable("presencas_no_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PublicacaoDoEncontro", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("IdentificadorDoEncontro")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_encontro");

                    b.Property<Guid>("IdentificadorDoUsuarioAutor")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_autor");

                    b.Property<string>("NomeOriginalDaMidia")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original_da_midia");

                    b.Property<DateTimeOffset>("PublicadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_em");

                    b.Property<long?>("TamanhoDaMidiaEmBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_da_midia_em_bytes");

                    b.Property<string>("Texto")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("texto");

                    b.Property<string>("TipoDeConteudoDaMidia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_de_conteudo_da_midia");

                    b.Property<string>("UrlDaMidia")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_da_midia");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioAutor");

                    b.HasIndex("IdentificadorDoEncontro", "PublicadoEm");

                    b.HasIndex("IdentificadorDoEncontro", "UrlDaMidia");

                    b.ToTable("publicacoes_do_encontro", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.ConviteDoGrupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset?>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EmailConvidado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_convidado");

                    b.Property<DateTimeOffset?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuarioQueConvidou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_convidou");

                    b.Property<DateTimeOffset?>("RecusadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recusado_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("EmailConvidado");

                    b.HasIndex("IdentificadorDoUsuarioQueConvidou");

                    b.HasIndex("IdentificadorDoGrupo", "EmailConvidado", "Situacao");

                    b.ToTable("convites_do_grupo", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("IdentificadorDoUsuarioDono")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_dono");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioDono");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("EntrouEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrou_em");

                    b.Property<Guid>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<DateTimeOffset?>("RemovidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removido_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuario");

                    b.HasIndex("IdentificadorDoGrupo", "IdentificadorDoUsuario")
                        .IsUnique();

                    b.ToTable("membros_do_grupo", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Identificador")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.Property<string>("UrlDaFotoDePerfil")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_da_foto_de_perfil");

                    b.HasKey("Identificador");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Autenticacao.TokenDeAtualizacao", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.Encontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueCriou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ItemDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueCriou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioResponsavel")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MemoriaDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQuePublicou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.MidiaDaMemoria", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.MemoriaDoEncontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDaMemoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.ParticipanteDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PresencaNoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoMembroDoGrupo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Encontros.PublicacaoDoEncontro", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Encontros.Encontro", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoEncontro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.ConviteDoGrupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany("Convites")
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueConvidou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioDono")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany("Membros")
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.Navigation("Convites");

                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
