// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoEncontros.Infraestrutura.Dados;

#nullable disable

namespace ProjetoEncontros.Infraestrutura.Dados.Migracoes
{
    [DbContext(typeof(ContextoDeBanco))]
    [Migration("20260701162436_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetoEncontros.Dominio.Autenticacao.TokenDeAtualizacao", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("HashDoToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_do_token");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.HasKey("Identificador");

                    b.HasIndex("HashDoToken")
                        .IsUnique();

                    b.HasIndex("IdentificadorDoUsuario");

                    b.ToTable("tokens_de_atualizacao", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.ConviteDoGrupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset?>("AceitoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceito_em");

                    b.Property<DateTimeOffset?>("CanceladoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("EmailConvidado")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_convidado");

                    b.Property<DateTimeOffset?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<Guid>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuarioQueConvidou")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_que_convidou");

                    b.Property<DateTimeOffset?>("RecusadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recusado_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("EmailConvidado");

                    b.HasIndex("IdentificadorDoUsuarioQueConvidou");

                    b.HasIndex("IdentificadorDoGrupo", "EmailConvidado", "Situacao");

                    b.ToTable("convites_do_grupo", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("IdentificadorDoUsuarioDono")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario_dono");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuarioDono");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset>("EntrouEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entrou_em");

                    b.Property<Guid>("IdentificadorDoGrupo")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_grupo");

                    b.Property<Guid>("IdentificadorDoUsuario")
                        .HasColumnType("uuid")
                        .HasColumnName("identificador_do_usuario");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("papel");

                    b.Property<DateTimeOffset?>("RemovidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removido_em");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("IdentificadorDoUsuario");

                    b.HasIndex("IdentificadorDoGrupo", "IdentificadorDoUsuario")
                        .IsUnique();

                    b.ToTable("membros_do_grupo", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("identificador");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("HashDaSenha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash_da_senha");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("situacao");

                    b.HasKey("Identificador");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Autenticacao.TokenDeAtualizacao", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.ConviteDoGrupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany("Convites")
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioQueConvidou")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuarioDono")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.MembroDoGrupo", b =>
                {
                    b.HasOne("ProjetoEncontros.Dominio.Grupos.Grupo", null)
                        .WithMany("Membros")
                        .HasForeignKey("IdentificadorDoGrupo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoEncontros.Dominio.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdentificadorDoUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjetoEncontros.Dominio.Grupos.Grupo", b =>
                {
                    b.Navigation("Convites");

                    b.Navigation("Membros");
                });
#pragma warning restore 612, 618
        }
    }
}
