<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ProjetoEncontros.Aplicacao\ProjetoEncontros.Aplicacao.csproj" />
    <ProjectReference Include="..\ProjetoEncontros.Infraestrutura\ProjetoEncontros.Infraestrutura.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ProjetoEncontros-Desenvolvimento</UserSecretsId>
  </PropertyGroup>

</Project>
